services:
  ssm-ui-ml: 
    build:
      context: .
    restart: unless-stopped
    network_mode: "host"
    environment:
      PROFILE: "dev"
      ML_DATABASE_HOST: "ssm-service-ml-database"
      ML_DATABASE_PORT: 5432
      ML_DATABASE_NAME: "ssm"
      ML_DATABASE_USER: "ssm"
      ML_DATABASE_PASSWORD: "password"
 
  ssm-keycloak:
    image: ghcr.io/smart-spectral-matching/ssm-keycloak:main-latest
    restart: unless-stopped
    network_mode: "host"
    ports:
      - "8080:8080"
    environment:
      KC_DB: "postgres"
      KC_DB_PASSWORD: postgres
      KC_DB_URL: jdbc:postgresql://localhost:5432/postgres
      KC_DB_USERNAME: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      HOSTNAME: localhost

  ssm-keycloak-postgres:
    image: postgres
    restart: unless-stopped
    network_mode: "host"
    environment:
      POSTGRES_PASSWORD: postgres
